# vim:set ft=tmux:
%hidden MODULE_NAME="gitmux"

# Requires https://github.com/arl/gitmux
set -ogq "@rosepine_${MODULE_NAME}_icon" "󰊢 "
set -ogqF "@rosepine_${MODULE_NAME}_color" "#{@thm_pine}"
set -gq "@rosepine_${MODULE_NAME}_text" '#(gitmux "#{pane_current_path}")'

source -F "#{d:current_file}/../utils/status_module.conf"
