# vim:set ft=tmux:
%hidden MODULE_NAME="kube"

# Requires https://github.com/jonmosco/kube-tmux

set -ogq "@rosepine_${MODULE_NAME}_icon" "󱃾 "
set -ogqF "@rosepine_${MODULE_NAME}_color" "#{@thm_blue}"
set -ogqF "@rosepine_kube_context_color" "#{@thm_red}"
set -ogqF "@rosepine_kube_namespace_color" "#{@thm_sky}"
set -ogq "@rosepine_${MODULE_NAME}_text" \
   "#(${TMUX_PLUGIN_MANAGER_PATH}kube-tmux/kube.tmux 250 #{@rosepine_kube_context_color} #{@rosepine_kube_namespace_color})"

source -F "#{d:current_file}/../utils/status_module.conf"
