# vim:set ft=tmux:
%hidden MODULE_NAME="user"

set -ogq @rosepine_user_icon " "
set -ogqF @rosepine_user_color "#{@thm_foam}"
set -ogq @rosepine_user_text "#(whoami)"

source -F "#{d:current_file}/../utils/status_module.conf"
