# vim:set ft=tmux:

# Embedded style that ensures that modules look "connected"
# when required.
set -gqF @_ctp_connect_style \
  "#{?#{==:#{@rosepine_status_connect_separator},yes},,#[bg=default]}"

set -gF "@rosepine_status_${MODULE_NAME}" \
  "#[fg=#{@rosepine_${MODULE_NAME}_color},nobold,nounderscore,noitalics]#{@_ctp_connect_style}#{@rosepine_status_left_separator}"

set -agF "@rosepine_status_${MODULE_NAME}" \
    "#[fg=#{@thm_base},bg=#{@rosepine_${MODULE_NAME}_color}]#{@rosepine_${MODULE_NAME}_icon}"

set -agF "@rosepine_status_${MODULE_NAME}" "#[fg=#{@rosepine_${MODULE_NAME}_color},"

# If _only_ the icon should be filled in, then change the background
# to surface_1, and the foreground to crust. Otherwise leave the formatting as-is.
%if "#{==:#{@rosepine_status_fill},icon}"
  set -agF "@rosepine_status_${MODULE_NAME}" "bg=#{@thm_surface}]#{@rosepine_status_middle_separator}#[fg=#{@thm_fg}] "
%else
  set -agF "@rosepine_status_${MODULE_NAME}" "]#{@rosepine_status_middle_separator}#[fg=#{@thm_base}]"
%endif

set -agF "@rosepine_status_${MODULE_NAME}" "#{@rosepine_${MODULE_NAME}_text}"

%if "#{==:#{@rosepine_status_fill},icon}"
  set -agF "@rosepine_status_${MODULE_NAME}" "#[fg=#{@thm_surface}]"
%else
  set -agF "@rosepine_status_${MODULE_NAME}" "#[fg=#{@rosepine_${MODULE_NAME}_color}]"
%endif

set -agF "@rosepine_status_${MODULE_NAME}" "#{@_ctp_connect_style}#{@rosepine_status_right_separator}"

set -ug @_ctp_connect_style
